In [6]:
import numpy as np
import pandas as pd


from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical


In [7]:
iris = load_iris()

X = iris.data
y = iris.target

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)


Feature Shape: (150, 4)
Target Shape: (150,)


In [8]:
y = to_categorical(y)

print("Encoded Target Example:")
print(y[:5])

Encoded Target Example:
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (120, 4)
Testing Data Shape: (30, 4)


In [11]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
model = Sequential()


model.add(Dense(
    units=16,
    activation='relu',
    input_dim=X_train.shape[1]
))

c:\Users\Hrishikesh Chandran\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.add(Dense(
    units=12,
    activation='relu'
))


model.add(Dense(
    units=8,
    activation='relu'
))


In [14]:
model.add(Dense(
    units=3,
    activation='softmax'
))

In [15]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           204 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 415 (1.62 KB)

 Trainable params: 415 (1.62 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=8,
    validation_split=0.2
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.2500 - loss: 1.0846 - val_accuracy: 0.2083 - val_loss: 1.0587
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4896 - loss: 1.0408 - val_accuracy: 0.4583 - val_loss: 1.0313
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5208 - loss: 1.0088 - val_accuracy: 0.5417 - val_loss: 1.0089
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5729 - loss: 0.9762 - val_accuracy: 0.6250 - val_loss: 0.9836
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6458 - loss: 0.9435 - val_accuracy: 0.6667 - val_loss: 0.9547
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7083 - loss: 0.9050 - val_accuracy: 0.7500 - val_loss: 0.9244
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7917 - loss: 0.8620 - val_accuracy: 0.8333 - val_loss: 0.8840
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.8115 - val_accuracy: 0.8750 - 

In [18]:
loss, accuracy = model.evaluate(X_test, y_test)

print("\nTest Accuracy:", accuracy)
print("Test Loss:", loss)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step - accuracy: 1.0000 - loss: 0.0220

Test Accuracy: 1.0
Test Loss: 0.02204127237200737


In [19]:
predictions = model.predict(X_test)

predicted_classes = np.argmax(predictions, axis=1)
actual_classes = np.argmax(y_test, axis=1)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


In [20]:
comparison = pd.DataFrame({
    'Actual Class': actual_classes,
    'Predicted Class': predicted_classes
})

print("\nPrediction Comparison:")
print(comparison.head(10))




Prediction Comparison:
   Actual Class  Predicted Class
0             1                1
1             0                0
2             2                2
3             1                1
4             1                1
5             0                0
6             1                1
7             2                2
8             1                1
9             1                1


In [21]:
new_sample = np.array([[5.1, 3.5, 1.4, 0.2]])

new_sample = scaler.transform(new_sample)

prediction = model.predict(new_sample)

predicted_class = np.argmax(prediction)

print("\nPredicted Flower Class:", predicted_class)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

Predicted Flower Class: 0


In [22]:
print("\nClass Names:")
print(iris.target_names)

print("\nPredicted Flower:")
print(iris.target_names[predicted_class])


Class Names:
['setosa' 'versicolor' 'virginica']

Predicted Flower:
setosa
